devices=("router", "switch", "firewall")
print(devices)
print(type(devices))
print(len(devices))
print(devices[1])
list_devices=list(devices)
list_devices.append("LB")
devices=tuple(list_devices)
print(devices)